### ISSUE TITLE
'setDismissTime' is not defined

### ISSUE THREAD

**Issue by brycesnyder** [uzochukwueddie/react-toast#5]
When attempting to compile, I keep getting this as an error.. Not sure where I would resolve this? 
```./src/App.js
  Line 106:5:  'setDismissTime' is not defined  no-undef

Search for the keywords to learn more about each error.```

**Comment by uzoeddie** [comment]
which of the files are you getting that error?

**Comment by gilav** [comment]
Hell, in App.js line 106

**Comment by gilav** [comment]
replace  setDismissTime with setAutoDeleteTime.
but still a few issues: autoDismissTime is value undefined when toast is created... I set it to a default (3000) when autodelete active and time undefined then it works.

**Comment by dev-codflaw** [comment]
> When attempting to compile, I keep getting this as an error.. Not sure where I would resolve this?
> 
> ```js
>   Line 106:5:  'setDismissTime' is not defined  no-undef
> 
> Search for the keywords to learn more about each error.```
> ```


Find the onInputChange function and replace by below code

const onInputChange = (e) => {
    const time = parseInt(e.target.value, 10);
    setAutoDeleteTime(time);
  }

**Comment by dev-codflaw** [comment]
> replace setDismissTime with setAutoDeleteTime.
> but still a few issues: autoDismissTime is value undefined when toast is created... I set it to a default (3000) when autodelete active and time undefined then it works.

**Replace Toast Component by the below code**
      <Toast 
        toastList={list}
        position={position}
        autoDelete={checkValue}
        dismissTime={autoDeleteTime}
      />

**Comment by dev-codflaw** [comment]
> replace setDismissTime with setAutoDeleteTime.
> but still a few issues: autoDismissTime is value undefined when toast is created... I set it to a default (3000) when autodelete active and time undefined then it works.

**Replace Toast component by the below code**

      <Toast 
        toastList={list}
        position={position}
        autoDelete={checkValue}
        dismissTime={autoDeleteTime}
      />
